server:
  port: 8082

spring:
  application:
    name: Sender-Service

  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:9092}
    topics:
      mailing: mailTopic
    consumer:
      group-id: mailing
      enable-auto-commit: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend_db}
    username: ${SPRING_DATASOURCE_USERNAME:backend_user}
    password: ${SPRING_DATASOURCE_PASSWORD:backend_password}

    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

database:
  observer:
    schedule: "0 0/1 * * * *"

io:
  reflectoring:
    kafka:
      bootstrap-servers: ${KAFKA_URL:http://localhost:9092}


