startup:
  mode: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:

  application:
    name: Main-Service

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
    default-schema: public

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend_db}
    username: ${SPRING_DATASOURCE_USERNAME:backend_user}
    password: ${SPRING_DATASOURCE_PASSWORD:backend_password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8180/realms/my_realm}
          jwk-set-uri: ${JWK_SET_URL:${spring.security.oauth2.resourceserver.jwt.issuer-uri}}/protocol/openid-connect/certs


logging:
  level:
    org:
      hibernate:
        SQL: ${startup.mode}
      springframework:
        security: ${startup.mode}


sorting:
  field: name





