startup:
  mode: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:

  application:
    name: Main-Service

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
    default-schema: public

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend_db}
    username: ${SPRING_DATASOURCE_USERNAME:backend_user}
    password: ${SPRING_DATASOURCE_PASSWORD:backend_password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: ${startup.mode}





